
name: Run Synthetic tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - name: Tests
        uses: cloudposse/github-action-docker-compose-test-run@main
        with:
          file: test/docker-compose.yml
          service: app
          command: regression-run/test.sh

