
name: Run Synthetic tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "disabled" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 
      - uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: './regression-run/docker-compose.yml'
          service: s3fs-tests

